<MainApp>

<MyFloatLayout>:
    canvas.before:
        Rectangle:
            size: self.size
            source: "assets/images/panel.png"
    ImageButton:  
        id:button1
        source:'assets/images/green_light.png'
        size_hint: .3, .3
        pos_hint:  {'center_x':.5, 'center_y':.75}
    Label:
        pos_hint:  {'center_x':.95, 'center_y':.05} 
        text: root.score
        font_size: '56sp'
        bold: True
        color: 0.3, 0.3, 0.3, 0.8